theme = "starter-blog"

day_night = true

font = "poppins"

font_size = "S"

site_type = "Person"

local_business_type = ""

org_name = ""

# Description for social sharing and search engines. If undefined, superuser role is used in place.
description = ""

highlight = true
highlight_languages = [
  "r",
  "go",
  "diff",
  "ocaml",
  "dart",
  "cpp",
  "dts",
  "bash",
  "arduino",
  "avrasm",
  "cmake",
  "dockerfile",
  "gcode",
  "makefile",
  "matlab",
  "nginx",
  "protobuf",
  "scala",
  "scss",
  "typescript",
  "verilog",
]

highlight_style = "shades-of-purple"

math = true

diagram = false

privacy_pack = false

edit_page = {repo_url = "", content_dir = "", repo_branch = "master", editable = {post = false}}

show_related = {post = true}

email = "ppeetteerrsx@gmail.com"

sharing_image = ""

twitter = ""

date_format = "Jan 2, 2006"

time_format = "3:04 PM"

address_format = "en-us"

main_menu = {align = "r", show_logo = true, highlight_active_link = true, show_language = false}

reading_time = true

section_pager = true

sharing = true

copyright_license = {enable = false, allow_derivatives = false, share_alike = true, allow_commercial = false, notice = "This work is licensed under {license}"}

highlight_superuser = false

link_authors = false

abstract_length = 135

plugins_js = []

[avatar]
gravatar = false

shape = "circle"

[comments]
engine = 0

commentable = {post = false}

[comments.disqus]
shortname = "" # Paste the shortname from your Disqus dashboard.
show_count = false # Show comment count in page header? (true/false)

[comments.commento]
url = ""
[search]
engine = 1

[search.algolia]
api_key = ""
app_id = ""
index_name = ""
show_logo = false

[map]
api_key = ""
engine = 0
zoom = 15

[marketing]
google_analytics = ""
google_tag_manager = ""

[cms]
netlify_cms = true

[icon.pack]
ai = true
